/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica;

import com.sun.org.apache.xml.internal.security.keys.content.MgmtData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author monyert
 */
public class Aplicacio extends javax.swing.JFrame {

    boolean nuez = false;
    boolean gafas = false;
    boolean pelo = false;
    boolean dientes = false;
    public graficador graf = new graficador();
    /**
     * Creates new form Aplicacio
     */
    public Aplicacio() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        jPanel13.add(graf,BorderLayout.CENTER);
    }

    public static void MensajeError() {
        JOptionPane.showMessageDialog(Aplicacio.jPanel13, "Sintaxis Incorrecta", "Error de Evaluacion", JOptionPane.CLOSED_OPTION);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        grup_so = new javax.swing.ButtonGroup();
        original_opt = new javax.swing.ButtonGroup();
        espill_opt = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radio_so_windows = new javax.swing.JRadioButton();
        radio_so_linux = new javax.swing.JRadioButton();
        radio_so_mac = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        box_prog = new javax.swing.JCheckBox();
        box_diss = new javax.swing.JCheckBox();
        box_adm = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        label_slider = new javax.swing.JLabel();
        form_boto_generar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        original_opt1 = new javax.swing.JRadioButton();
        original_opt2 = new javax.swing.JRadioButton();
        original_opt3 = new javax.swing.JRadioButton();
        original_check1 = new javax.swing.JCheckBox();
        original_check2 = new javax.swing.JCheckBox();
        original_check3 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        original_text_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        espill_opt4 = new javax.swing.JRadioButton();
        espill_opt5 = new javax.swing.JRadioButton();
        espill_opt6 = new javax.swing.JRadioButton();
        espill_check4 = new javax.swing.JCheckBox();
        espill_check5 = new javax.swing.JCheckBox();
        espill_check6 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        espill_text_field1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel12 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nom_pelicula = new javax.swing.JTextField();
        boto_afegir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        box_pelicules = new javax.swing.JComboBox<>();
        cal_0 = new javax.swing.JButton();
        cal_dot = new javax.swing.JButton();
        cal_res = new javax.swing.JButton();
        cal_1 = new javax.swing.JButton();
        cal_2 = new javax.swing.JButton();
        cal_3 = new javax.swing.JButton();
        cal_4 = new javax.swing.JButton();
        cal_6 = new javax.swing.JButton();
        cal_5 = new javax.swing.JButton();
        cal_7 = new javax.swing.JButton();
        cal_8 = new javax.swing.JButton();
        cal_9 = new javax.swing.JButton();
        cal_ce = new javax.swing.JButton();
        cal_mult = new javax.swing.JButton();
        cal_div = new javax.swing.JButton();
        cal_sum = new javax.swing.JButton();
        cal_rest = new javax.swing.JButton();
        cal_resultado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        numero_a = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        numero_b = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        numero_c = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        boto_calcular = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        splitpane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_img = new javax.swing.JList<>();
        label_img = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        var_nuez = new javax.swing.JCheckBox();
        var_gafas = new javax.swing.JCheckBox();
        var_pelo = new javax.swing.JCheckBox();
        var_dientes = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        label_persona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Tria un Sistema Operatiu:");

        radio_so_windows.setBackground(new java.awt.Color(204, 255, 204));
        grup_so.add(radio_so_windows);
        radio_so_windows.setText("Windows");

        radio_so_linux.setBackground(new java.awt.Color(204, 255, 204));
        grup_so.add(radio_so_linux);
        radio_so_linux.setText("Linux");

        radio_so_mac.setBackground(new java.awt.Color(204, 255, 204));
        grup_so.add(radio_so_mac);
        radio_so_mac.setText("Mac");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel2.setText("Tria la teua especialitat:");

        box_prog.setBackground(new java.awt.Color(204, 255, 204));
        box_prog.setText("Programació");
        box_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_progActionPerformed(evt);
            }
        });

        box_diss.setBackground(new java.awt.Color(204, 255, 204));
        box_diss.setText("Disseny");

        box_adm.setBackground(new java.awt.Color(204, 255, 204));
        box_adm.setText("Administració");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel3.setText("Hores que li dediques a l'ordinador:");

        slider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderMouseDragged(evt);
            }
        });
        slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sliderMouseClicked(evt);
            }
        });

        label_slider.setText("50");

        form_boto_generar.setText("Generar");
        form_boto_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_boto_generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box_adm)
                            .addComponent(box_diss)
                            .addComponent(box_prog)
                            .addComponent(radio_so_mac)
                            .addComponent(radio_so_linux)
                            .addComponent(radio_so_windows)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(label_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(form_boto_generar)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(radio_so_windows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_so_linux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_so_mac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(box_prog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_diss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_adm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(form_boto_generar)
                .addGap(117, 117, 117))
        );

        jPanel10.setBackground(new java.awt.Color(102, 255, 51));

        jLabel4.setText("Original");

        original_opt1.setBackground(new java.awt.Color(102, 255, 51));
        original_opt.add(original_opt1);
        original_opt1.setText("Opcio 1");
        original_opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_opt1ActionPerformed(evt);
            }
        });

        original_opt2.setBackground(new java.awt.Color(102, 255, 51));
        original_opt.add(original_opt2);
        original_opt2.setText("Opcio 2");
        original_opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_opt2ActionPerformed(evt);
            }
        });

        original_opt3.setBackground(new java.awt.Color(102, 255, 51));
        original_opt.add(original_opt3);
        original_opt3.setText("Opcio 3");
        original_opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_opt3ActionPerformed(evt);
            }
        });

        original_check1.setBackground(new java.awt.Color(102, 255, 51));
        original_check1.setText("Opcio 4");
        original_check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_check1ActionPerformed(evt);
            }
        });

        original_check2.setBackground(new java.awt.Color(102, 255, 51));
        original_check2.setText("Opcio 5");
        original_check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_check2ActionPerformed(evt);
            }
        });

        original_check3.setBackground(new java.awt.Color(102, 255, 51));
        original_check3.setText("Opcio 6");
        original_check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                original_check3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Text:");

        jLabel7.setText("Combo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Spinner:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(original_opt1)
                                    .addComponent(original_opt2)
                                    .addComponent(original_opt3))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(original_check3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(original_check2)
                                            .addComponent(original_check1))
                                        .addGap(186, 186, 186)
                                        .addComponent(jLabel6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(original_text_field)
                            .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(original_opt1)
                            .addComponent(original_check1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(original_opt2)
                            .addComponent(original_check2)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(original_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(original_opt3)
                    .addComponent(original_check3)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 255, 0));
        jPanel11.setEnabled(false);

        jLabel5.setText("Espill");
        jLabel5.setEnabled(false);

        espill_opt4.setBackground(new java.awt.Color(204, 255, 0));
        espill_opt.add(espill_opt4);
        espill_opt4.setText("Opcio 1");
        espill_opt4.setEnabled(false);

        espill_opt5.setBackground(new java.awt.Color(204, 255, 0));
        espill_opt.add(espill_opt5);
        espill_opt5.setText("Opcio 2");
        espill_opt5.setEnabled(false);

        espill_opt6.setBackground(new java.awt.Color(204, 255, 0));
        espill_opt.add(espill_opt6);
        espill_opt6.setText("Opcio 3");
        espill_opt6.setEnabled(false);

        espill_check4.setBackground(new java.awt.Color(204, 255, 0));
        espill_check4.setText("Opcio 4");
        espill_check4.setEnabled(false);

        espill_check5.setBackground(new java.awt.Color(204, 255, 0));
        espill_check5.setText("Opcio 5");
        espill_check5.setEnabled(false);

        espill_check6.setBackground(new java.awt.Color(204, 255, 0));
        espill_check6.setText("Opcio 6");
        espill_check6.setEnabled(false);

        jLabel9.setText("Text:");
        jLabel9.setEnabled(false);

        espill_text_field1.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, original_text_field, org.jdesktop.beansbinding.ELProperty.create("${text}"), espill_text_field1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel10.setText("Combo:");
        jLabel10.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setEnabled(false);

        jLabel11.setText("Spinner:");
        jLabel11.setEnabled(false);

        jSpinner2.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinner1, org.jdesktop.beansbinding.ELProperty.create("${value}"), jSpinner2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(espill_opt4)
                                    .addComponent(espill_opt5)
                                    .addComponent(espill_opt6))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(espill_check6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(espill_check5)
                                            .addComponent(espill_check4))
                                        .addGap(189, 189, 189)
                                        .addComponent(jLabel9)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espill_text_field1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 150, Short.MAX_VALUE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espill_opt4)
                            .addComponent(espill_check4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espill_opt5)
                            .addComponent(espill_check5)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(espill_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espill_opt6)
                            .addComponent(espill_check6)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Formulari", jPanel5);

        jLabel15.setText("Pelicula");

        boto_afegir.setText("Afegir");
        boto_afegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_afegirActionPerformed(evt);
            }
        });

        jLabel16.setText("Pelicules");

        cal_0.setText("0");
        cal_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_dot.setText(".");
        cal_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_res.setText("=");
        cal_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_1.setText("1");
        cal_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_2.setText("2");
        cal_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_3.setText("3");
        cal_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_4.setText("4");
        cal_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_6.setText("6");
        cal_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_5.setText("5");
        cal_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_7.setText("7");
        cal_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_8.setText("8");
        cal_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_9.setText("9");
        cal_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_ce.setText("CE");
        cal_ce.setMaximumSize(new java.awt.Dimension(39, 23));
        cal_ce.setMinimumSize(new java.awt.Dimension(39, 23));
        cal_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_mult.setText("*");
        cal_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_div.setText("/");
        cal_div.setMaximumSize(new java.awt.Dimension(39, 23));
        cal_div.setMinimumSize(new java.awt.Dimension(39, 23));
        cal_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_sum.setText("+");
        cal_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_rest.setText("-");
        cal_rest.setMaximumSize(new java.awt.Dimension(39, 23));
        cal_rest.setMinimumSize(new java.awt.Dimension(39, 23));
        cal_rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_5ActionPerformed(evt);
            }
        });

        cal_resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(52, 52, 52)
                        .addComponent(boto_afegir))
                    .addComponent(nom_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box_pelicules, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cal_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cal_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cal_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cal_div, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cal_rest, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cal_7, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cal_8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cal_9, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cal_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cal_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                            .addComponent(cal_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cal_2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                                    .addComponent(cal_5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cal_6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                                    .addComponent(cal_3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                                            .addComponent(cal_dot, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cal_sum, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(cal_res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(boto_afegir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nom_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(box_pelicules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(cal_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal_ce, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cal_mult, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cal_div, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cal_rest, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cal_7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cal_9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(cal_8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cal_4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(cal_5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(cal_6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                    .addComponent(cal_sum, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cal_1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(cal_2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(cal_3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cal_dot, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(cal_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cal_res, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jLabel12.setText("a:");

        numero_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_aActionPerformed(evt);
            }
        });

        jLabel13.setText("b:");

        numero_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_bActionPerformed(evt);
            }
        });

        jLabel14.setText("c:");

        numero_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_cActionPerformed(evt);
            }
        });

        jPanel13.setLayout(new java.awt.BorderLayout());

        boto_calcular.setText("Calcular");
        boto_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero_a, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero_b, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero_c, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boto_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_c, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(numero_b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(numero_a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(boto_calcular))
        );

        boto_calcular.getAccessibleContext().setAccessibleDescription("");
        boto_calcular.getAccessibleContext().setAccessibleParent(jLabel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Calc i Grafica", jPanel6);

        splitpane.setDividerLocation(180);
        splitpane.setLastDividerLocation(180);

        lista_img.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Primer", "Segon", "Tercer" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_imgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_img);

        splitpane.setLeftComponent(jScrollPane1);
        splitpane.setRightComponent(label_img);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Partit", jPanel7);

        var_nuez.setText("Nuez");
        var_nuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_nuezActionPerformed(evt);
            }
        });

        var_gafas.setText("Gafas");
        var_gafas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_gafasActionPerformed(evt);
            }
        });

        var_pelo.setText("Pelo");
        var_pelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_peloActionPerformed(evt);
            }
        });

        var_dientes.setText("Dientes");
        var_dientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_dientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        label_persona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Practica/geek/geek-----.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(var_gafas)
                    .addComponent(var_dientes)
                    .addComponent(var_nuez)
                    .addComponent(var_pelo))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_persona)
                        .addGap(93, 93, 93)))
                .addContainerGap(681, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(var_nuez)
                .addGap(77, 77, 77)
                .addComponent(var_gafas)
                .addGap(98, 98, 98)
                .addComponent(var_pelo)
                .addGap(104, 104, 104)
                .addComponent(var_dientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(label_persona)
                .addGap(362, 362, 362))
        );

        jTabbedPane1.addTab("CheckBox", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_progActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_progActionPerformed

    private void sliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseDragged
        label_slider.setText(Integer.toString(slider.getValue()));
    }//GEN-LAST:event_sliderMouseDragged

    private void form_boto_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_boto_generarActionPerformed
        //Generar un cuadre de text amb les dades marcades.
        try{
        radio_so_windows.setActionCommand("Windows");
        radio_so_linux.setActionCommand("Linux");
        radio_so_mac.setActionCommand("Mac");
        String sistema = grup_so.getSelection().getActionCommand();
        String valor1 = "", valor2 = "", valor3 = "";
        if (box_prog.isSelected()) {
            valor1 = "\n  Programació";
        }
        if (box_diss.isSelected()) {
            valor2 = "\n  Disseny";
        }
        if (box_adm.isSelected()) {
            valor3 = "\n  Administració";
        }
        String bola = Integer.toString(slider.getValue());

        JOptionPane.showMessageDialog(this,
                "Resultat de la Enquesta" + "\n"
                + "Sistema: " + sistema + "\n"
                + "Especialitat:"
                + valor1
                + valor2
                + valor3
                + "\nHores: " + bola, "Datos Introducidos", JOptionPane.PLAIN_MESSAGE);
        }catch(NullPointerException buit){
            JOptionPane.showMessageDialog(this,"Els camps estan buits!!. \n Torna a Intentar-ho.","Avis",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_form_boto_generarActionPerformed

    private void original_opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_opt1ActionPerformed
        if (original_opt1.isSelected()) {
            espill_opt4.setSelected(true);
        }
    }//GEN-LAST:event_original_opt1ActionPerformed

    private void original_opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_opt2ActionPerformed
        if (original_opt2.isSelected()) {
            espill_opt5.setSelected(true);
        }
    }//GEN-LAST:event_original_opt2ActionPerformed

    private void original_opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_opt3ActionPerformed
        if (original_opt3.isSelected()) {
            espill_opt6.setSelected(true);
        }
    }//GEN-LAST:event_original_opt3ActionPerformed

    private void original_check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_check1ActionPerformed
        if (original_check1.isSelected()) {
            espill_check4.setSelected(true);
        } else {
            espill_check4.setSelected(false);
        }
    }//GEN-LAST:event_original_check1ActionPerformed

    private void original_check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_check2ActionPerformed
        if (original_check2.isSelected()) {
            espill_check5.setSelected(true);
        } else {
            espill_check5.setSelected(false);
        }
    }//GEN-LAST:event_original_check2ActionPerformed

    private void original_check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_original_check3ActionPerformed
        if (original_check3.isSelected()) {
            espill_check6.setSelected(true);
        } else {
            espill_check6.setSelected(false);
        }
    }//GEN-LAST:event_original_check3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.setSelectedIndex(jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void boto_afegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_afegirActionPerformed
        String peli = nom_pelicula.getText();
        box_pelicules.addItem(peli);
        nom_pelicula.setText("");
    }//GEN-LAST:event_boto_afegirActionPerformed

    private void cal_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal_5ActionPerformed
        ScriptEngineManager script = new ScriptEngineManager();
        ScriptEngine eng = script.getEngineByName("JavaScript");

        String opcio = evt.getActionCommand();
        //System.out.println(opcio);
        String temp = "";
        String total = "";
        switch (opcio) {
            case "CE": {
                cal_resultado.setText("");
            }
            break;
            case "*": {
                temp = cal_resultado.getText() + "*";
            }
            break;
            case "/": {
                temp = cal_resultado.getText() + "/";
            }
            break;
            case "-": {
                temp = cal_resultado.getText() + "-";
            }
            break;
            case "7": {
                temp = cal_resultado.getText() + "7";
            }
            break;
            case "8": {
                temp = cal_resultado.getText() + "8";
            }
            break;
            case "9": {
                temp = cal_resultado.getText() + "9";
            }
            break;
            case "+": {
                temp = cal_resultado.getText() + "+";
            }
            break;
            case "4": {
                temp = cal_resultado.getText() + "4";
            }
            break;
            case "5": {
                temp = cal_resultado.getText() + "5";
            }
            break;
            case "6": {
                temp = cal_resultado.getText() + "6";
            }
            break;
            case "1": {
                temp = cal_resultado.getText() + "1";
            }
            break;
            case "2": {
                temp = cal_resultado.getText() + "2";
            }
            break;
            case "3": {
                temp = cal_resultado.getText() + "3";
            }
            break;
            case "0": {
                temp = cal_resultado.getText() + "0";
            }
            break;
            case ".": {
                temp = cal_resultado.getText() + ".";
            }
            break;
            case "=": {
                temp = cal_resultado.getText();
                try {
                    total = eng.eval(temp).toString();
                    //System.out.println(total);
                } catch (ScriptException ex) {
                    System.out.println("Error");;
                }
            }
            break;
        }
        if (opcio.equals("=")) {
            cal_resultado.setText(total);
        } else {
            cal_resultado.setText(temp);
        }

    }//GEN-LAST:event_cal_5ActionPerformed

    private void lista_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_imgMouseClicked
        ImageIcon img;
        int seleccio = lista_img.getSelectedIndex();

        switch (seleccio) {
            case 0:
                img = new ImageIcon(getClass().getResource("gat.jpeg"));
                label_img.setIcon(img);
                break;
            case 1:
                img = new ImageIcon(getClass().getResource("dofi.jpeg"));
                label_img.setIcon(img);
                break;
            case 2:
                img = new ImageIcon(getClass().getResource("ratoli.jpeg"));
                label_img.setIcon(img);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_lista_imgMouseClicked

    private void var_nuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_nuezActionPerformed
        if (var_nuez.isSelected()) {
            nuez = true;
            //System.out.println("True");
        } else {
            nuez = false;
            //System.out.println("False");
        }
        if (var_gafas.isSelected()) {
            gafas = true;
            //System.out.println("True");
        } else {
            gafas = false;
           //System.out.println("False");
        }
        if (var_pelo.isSelected()) {
            pelo = true;
            //System.out.println("True");
        } else {
            pelo = false;
            //System.out.println("False");
        }
        if (var_dientes.isSelected()) {
            dientes = true;
            //System.out.println("True");
        } else {
            dientes = false;
            //System.out.println("False");
        }
        
       ImageIcon persona;
        if (dientes == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek----t.gif"));
            label_persona.setIcon(persona);
        }
        if (pelo == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek---h-.gif"));
            label_persona.setIcon(persona);
        }
        if ((pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek---ht.gif"));
            label_persona.setIcon(persona);
        }
        if (gafas == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g--.gif"));
            label_persona.setIcon(persona);
        }
        if ((gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--gh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--ght.gif"));
            label_persona.setIcon(persona);
        } 
        if (nuez == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c---.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c--t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-h-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-ht.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg--.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cgh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cght.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == false)&&(gafas == false)&&(pelo == false)&&(dientes == false)){
            persona = new ImageIcon(getClass().getResource("geek/geek-----.gif"));
            label_persona.setIcon(persona);
        }
       
    }//GEN-LAST:event_var_nuezActionPerformed

    private void var_gafasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_gafasActionPerformed
        if (var_nuez.isSelected()) {
            nuez = true;
            //System.out.println("True");
        } else {
            nuez = false;
            //System.out.println("False");
        }
        if (var_gafas.isSelected()) {
            gafas = true;
            //System.out.println("True");
        } else {
            gafas = false;
            //System.out.println("False");
        }
        if (var_pelo.isSelected()) {
            pelo = true;
            //System.out.println("True");
        } else {
            pelo = false;
            //System.out.println("False");
        }
        if (var_dientes.isSelected()) {
            dientes = true;
            //System.out.println("True");
        } else {
            dientes = false;
            //System.out.println("False");
        }
        
       ImageIcon persona;
        if (dientes == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek----t.gif"));
            label_persona.setIcon(persona);
        }
        if (pelo == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek---h-.gif"));
            label_persona.setIcon(persona);
        }
        if ((pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek---ht.gif"));
            label_persona.setIcon(persona);
        }
        if (gafas == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g--.gif"));
            label_persona.setIcon(persona);
        }
        if ((gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--gh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--ght.gif"));
            label_persona.setIcon(persona);
        } 
        if (nuez == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c---.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c--t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-h-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-ht.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg--.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cgh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cght.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == false)&&(gafas == false)&&(pelo == false)&&(dientes == false)){
            persona = new ImageIcon(getClass().getResource("geek/geek-----.gif"));
            label_persona.setIcon(persona);
        }
        
    }//GEN-LAST:event_var_gafasActionPerformed

    private void var_peloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_peloActionPerformed
        if (var_nuez.isSelected()) {
            nuez = true;
            //System.out.println("True");
        } else {
            nuez = false;
            //System.out.println("False");
        }
        if (var_gafas.isSelected()) {
            gafas = true;
            //System.out.println("True");
        } else {
            gafas = false;
            //System.out.println("False");
        }
        if (var_pelo.isSelected()) {
            pelo = true;
            //System.out.println("True");
        } else {
            pelo = false;
            //System.out.println("False");
        }
        if (var_dientes.isSelected()) {
            dientes = true;
            //System.out.println("True");
        } else {
            dientes = false;
            //System.out.println("False");
        }
        
       ImageIcon persona;
        if (dientes == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek----t.gif"));
            label_persona.setIcon(persona);
        }
        if (pelo == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek---h-.gif"));
            label_persona.setIcon(persona);
        }
        if ((pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek---ht.gif"));
            label_persona.setIcon(persona);
        }
        if (gafas == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g--.gif"));
            label_persona.setIcon(persona);
        }
        if ((gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--gh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--ght.gif"));
            label_persona.setIcon(persona);
        } 
        if (nuez == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c---.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c--t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-h-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-ht.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg--.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cgh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cght.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == false)&&(gafas == false)&&(pelo == false)&&(dientes == false)){
            persona = new ImageIcon(getClass().getResource("geek/geek-----.gif"));
            label_persona.setIcon(persona);
        }
    }//GEN-LAST:event_var_peloActionPerformed

    private void var_dientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_dientesActionPerformed
        if (var_nuez.isSelected()) {
            nuez = true;
            //System.out.println("True");
        } else {
            nuez = false;
            //System.out.println("False");
        }
        if (var_gafas.isSelected()) {
            gafas = true;
            //System.out.println("True");
        } else {
            gafas = false;
            //System.out.println("False");
        }
        if (var_pelo.isSelected()) {
            pelo = true;
            //System.out.println("True");
        } else {
            pelo = false;
            //System.out.println("False");
        }
        if (var_dientes.isSelected()) {
            dientes = true;
            //System.out.println("True");
        } else {
            dientes = false;
            //System.out.println("False");
        }
        
       ImageIcon persona;
        if (dientes == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek----t.gif"));
            label_persona.setIcon(persona);
        }
        if (pelo == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek---h-.gif"));
            label_persona.setIcon(persona);
        }
        if ((pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek---ht.gif"));
            label_persona.setIcon(persona);
        }
        if (gafas == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g--.gif"));
            label_persona.setIcon(persona);
        }
        if ((gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--g-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--gh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek--ght.gif"));
            label_persona.setIcon(persona);
        } 
        if (nuez == true) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c---.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c--t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-h-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-c-ht.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg--.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cg-t.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cgh-.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == true) && (gafas == true) && (pelo == true) && (dientes == true)) {
            persona = new ImageIcon(getClass().getResource("geek/geek-cght.gif"));
            label_persona.setIcon(persona);
        } 
        if ((nuez == false)&&(gafas == false)&&(pelo == false)&&(dientes == false)){
            persona = new ImageIcon(getClass().getResource("geek/geek-----.gif"));
            label_persona.setIcon(persona);
        }
    }//GEN-LAST:event_var_dientesActionPerformed

    private void sliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseClicked
        label_slider.setText(Integer.toString(slider.getValue()));
    }//GEN-LAST:event_sliderMouseClicked

    private void numero_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_cActionPerformed

    private void numero_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_bActionPerformed

    private void numero_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_aActionPerformed

    private void boto_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_calcularActionPerformed
            graf.repaint();
    }//GEN-LAST:event_boto_calcularActionPerformed

   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boto_afegir;
    public static javax.swing.JButton boto_calcular;
    private javax.swing.JCheckBox box_adm;
    private javax.swing.JCheckBox box_diss;
    private javax.swing.JComboBox<String> box_pelicules;
    private javax.swing.JCheckBox box_prog;
    private javax.swing.JButton cal_0;
    private javax.swing.JButton cal_1;
    private javax.swing.JButton cal_2;
    private javax.swing.JButton cal_3;
    private javax.swing.JButton cal_4;
    private javax.swing.JButton cal_5;
    private javax.swing.JButton cal_6;
    private javax.swing.JButton cal_7;
    private javax.swing.JButton cal_8;
    private javax.swing.JButton cal_9;
    private javax.swing.JButton cal_ce;
    private javax.swing.JButton cal_div;
    private javax.swing.JButton cal_dot;
    private javax.swing.JButton cal_mult;
    private javax.swing.JButton cal_res;
    private javax.swing.JButton cal_rest;
    private javax.swing.JTextField cal_resultado;
    private javax.swing.JButton cal_sum;
    private javax.swing.JCheckBox espill_check4;
    private javax.swing.JCheckBox espill_check5;
    private javax.swing.JCheckBox espill_check6;
    private javax.swing.ButtonGroup espill_opt;
    private javax.swing.JRadioButton espill_opt4;
    private javax.swing.JRadioButton espill_opt5;
    private javax.swing.JRadioButton espill_opt6;
    private javax.swing.JTextField espill_text_field1;
    private javax.swing.JButton form_boto_generar;
    private javax.swing.ButtonGroup grup_so;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    public static javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_persona;
    private javax.swing.JLabel label_slider;
    private javax.swing.JList<String> lista_img;
    private javax.swing.JTextField nom_pelicula;
    public static javax.swing.JTextField numero_a;
    public static javax.swing.JTextField numero_b;
    public static javax.swing.JTextField numero_c;
    private javax.swing.JCheckBox original_check1;
    private javax.swing.JCheckBox original_check2;
    private javax.swing.JCheckBox original_check3;
    private javax.swing.ButtonGroup original_opt;
    private javax.swing.JRadioButton original_opt1;
    private javax.swing.JRadioButton original_opt2;
    private javax.swing.JRadioButton original_opt3;
    private javax.swing.JTextField original_text_field;
    private javax.swing.JRadioButton radio_so_linux;
    private javax.swing.JRadioButton radio_so_mac;
    private javax.swing.JRadioButton radio_so_windows;
    private javax.swing.JSlider slider;
    private javax.swing.JSplitPane splitpane;
    private javax.swing.JCheckBox var_dientes;
    private javax.swing.JCheckBox var_gafas;
    private javax.swing.JCheckBox var_nuez;
    private javax.swing.JCheckBox var_pelo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
